# @package _global_
module:
  _target_: emg2qwerty.models.transformer_ctc.TransformerCTCModule
  electrode_channels: 16
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  transformer_dim: 256
  transformer_heads: 4
  transformer_layers: 3
  transformer_ff_dim: 512
  transformer_dropout: 0.2
  temporal_stride: 2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
